### ISSUE TITLE
REQUEST: Create wallets to fund Ideas/Improvements.

### ISSUE THREAD

**Issue by TOGM** [Brandantl/Monero-TipBot#1]
Hey there, been watching your repo, great job by the way. I was curious if there was a way to fund a wallet for bounties. 

For example to create bounty, 
 `!createbounty <TotalAmount> <Request> <Description> `

Bot Response:
` "<Username> created a bounty for <Description> for <TotalAmount> ITNS"`

Then, people would donate to the wallet by using:
`!donate <Request> <Amount>`

Bot Response:
`"<Username> donated <Amount> ITNS for <Description>. You can contribute to the cause by using !donate <Request> amount"`

To show bounties:
`!showbounty ALL`
to show all
and:
`!showbounty <request>`
to see a specific bounty

Part of the wallet creation would have to be creating a viewkey/ allowing the users to see how much is funded.

**Comment by Brandantl** [comment]
Yeah and I think you can implement that using the code from Lottery.cpp/h which makes a custom wallet called lottery which that class manages.

**Comment by Brandantl** [comment]
Implemented into develop.
