### ISSUE TITLE
Welcome Bonus

### ISSUE THREAD

**Issue by lorvent** [Brandantl/Monero-TipBot#7]
Hi,
it is an interesting application :)

is it possible to add a welcome bonus to each user?
i.e. upon joining discord, we can give them say 10 coins....
is that possible?

thanks.

**Comment by TylerTheFox** [comment]
Misclicked. 

I believe you can do it using this function of the discod api virtual void onMember            (Snowflake<Server> serverID, ServerMember member);

Just note youll be giving a lot of coins to spam bots.

**Comment by lorvent** [comment]
hmm yeah....

can we have something like only after they do some captcha or after 24hrs like that?

i mean.....such thing is possible using discord?

thanks

**Comment by TylerTheFox** [comment]
You can have users use the !take faucet command instead of automatically giving it to them. Just set the timer to like years before they can use it again.

**Comment by lorvent** [comment]
ok thanks,

have a great day ahead!

**Comment by TylerTheFox** [comment]
FYI The take command only works for users who've had a Discord account for more than 7 days, but you can adjust that in the settings.

**Comment by lorvent** [comment]
Ah! thats a good setting against spammers :)
